version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Paris"
    allow:
      - dependency-type: "direct"
        dependencies:
          - "@citizenfx/client"
          - "@citizenfx/server"
          - "cross-fetch"
          - "reflect-metadata"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Chore"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:00"
      timezone: "Europe/Paris"
    allow:
      - dependency-type: "direct"
        dependencies:
          - "@citizenfx/client"
          - "@citizenfx/server"
          - "cross-fetch"
          - "reflect-metadata"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Chore"
    open-pull-requests-limit: 5
