version: 2.1

executors:
  node-executor:
    docker:
      - image: node:current-alpine3.19
    working_directory: ~/repo

jobs:
  checkout:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

  install:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - store_test_results:
          path: ./test-results
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Lint
          command: npm run lint

  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Build
          command: npm run build

workflows:
  version: 2
  test_and_build:
    jobs:
      - checkout
      - install:
          requires:
            - checkout
      - test:
          requires:
            - install
      - build:
          requires:
            - test
