export enum ServerEventNames {
    EntityCreated = 'entityCreated',
    EntityCreating = 'entityCreating',
    EntityRemoved = 'entityRemoved',
    OnResourceListRefresh = 'onResourceListRefresh',
    OnResourceStart = 'onResourceStart',
    OnResourceStarting = 'onResourceStarting',
    OnResourceStop = 'onResourceStop',
    OnServerResourceStart = 'onServerResourceStart',
    OnServerResourceStop = 'onServerResourceStop',
    PlayerConnecting = 'playerConnecting',
    PlayerEnteredScope = 'playerEnteredScope',
    PlayerJoining = 'playerJoining',
    PlayerLeftScope = 'playerLeftScope',
    PtFxEvent = 'ptFxEvent',
    RemoveAllWeaponsEvent = 'removeAllWeaponsEvent',
    StartProjectileEvent = 'startProjectileEvent',
    WeaponDamageEvent = 'weaponDamageEvent',
}
