export enum WeaponsEnum {
	Unknown = -1,

	/* Melees */
	Dagger = 'weapon_dagger',
	Bat = 'weapon_bat',
	Bottle = 'weapon_bottle',
	Crowbar = 'weapon_crowbar',
	Unarmed = 'weapon_unarmed',
	Flashlight = 'weapon_flashlight',
	GolfClub = 'weapon_golfclub',
	Hammer = 'weapon_hammer',
	Hatchet = 'weapon_hatchet',
	Knuckle = 'weapon_knuckle',
	Knife = 'weapon_knife',
	Machete = 'weapon_machete',
	Switchblade = 'weapon_switchblade',
	Nightstick = 'weapon_nightstick',
	PipeWrench = 'weapon_wrench',
	BattleAxe = 'weapon_battleaxe',
	PoolCue = 'weapon_poolcue',
	StoneHatchet = 'weapon_stone_hatchet',
	CandyCane = 'weapon_candycane',
	StunRod = 'weapon_stunrod',

	/* Handguns */
	Pistol = 'weapon_pistol',
	PistolMk2 = 'weapon_pistol_mk2',
	CombatPistol = 'weapon_combatpistol',
	ApPistol = 'weapon_appistol',
	StunGun = 'weapon_stungun',
	Pistol50 = 'weapon_pistol50',
	SnsPistol = 'weapon_snspistol',
	SnsPistolMk2 = 'weapon_snspistol_mk2',
	HeavyPistol = 'weapon_heavypistol',
	VintagePistol = 'weapon_vintagepistol',
	FlareGun = 'weapon_flaregun',
	MarksmanPistol = 'weapon_marksmanpistol',
	Revolver = 'weapon_revolver',
	RevolverMk2 = 'weapon_revolver_mk2',
	DoubleActionRevolver = 'weapon_doubleaction',
	RayPistol = 'weapon_raypistol',
	CeramicPistol = 'weapon_ceramicpistol',
	NavyRevolver = 'weapon_navyrevolver',
	GadgetPistol = 'weapon_gadgetpistol',
	StunGunMp = 'weapon_stungun_mp',
	PistolXm3 = 'weapon_pistolxm3',

	/* Submachines Guns */
	MicroSmg = 'weapon_microsmg',
	Smg = 'weapon_smg',
	SmgMk2 = 'weapon_smg_mk2',
	AssaultSmg = 'weapon_assaultsmg',
	CombatPdw = 'weapon_combatpdw',
	MachinePistol = 'weapon_machinepistol',
	MiniSmg = 'weapon_minismg',
	RayCarbine = 'weapon_raycarbine',
	TecPistol = 'weapon_tecpistol',

	/* Shotguns */
	PumpShotgun = 'weapon_pumpshotgun',
	PumpShotgunMk2 = 'weapon_pumpshotgun_mk2',
	SawnOffShotgun = 'weapon_sawnoffshotgun',
	AssaultShotgun = 'weapon_assaultshotgun',
	BullpupShotgun = 'weapon_bullpupshotgun',
	Musket = 'weapon_musket',
	HeavyShotgun = 'weapon_heavyshotgun',
	DoubleBarrelShotgun = 'weapon_dbshotgun',
	SweeperShotgun = 'weapon_autoshotgun',
	CombatShotgun = 'weapon_combatshotgun',

	/* Assault Rifles */
	AssaultRifle = 'weapon_assaultrifle',
	AssaultRifleMk2 = 'weapon_assaultrifle_mk2',
	CarbineRifle = 'weapon_carbinerifle',
	CarbineRifleMk2 = 'weapon_carbinerifle_mk2',
	AdvancedRifle = 'weapon_advancedrifle',
	SpecialCarbine = 'weapon_specialcarbine',
	SpecialCarbineMk2 = 'weapon_specialcarbine_mk2',
	BullpupRifle = 'weapon_bullpuprifle',
	BullpupRifleMk2 = 'weapon_bullpuprifle_mk2',
	CompactRifle = 'weapon_compactrifle',
	MilitaryRifle = 'weapon_militaryrifle',
	HeavyRifle = 'weapon_heavyrifle',
	TacticalRifle = 'weapon_tacticalrifle',
	BattleRifle = 'weapon_battlerifle',

	/* Light Machine Guns */
	Mg = 'weapon_mg',
	CombatMg = 'weapon_combatmg',
	CombatMgMk2 = 'weapon_combatmg_mk2',
	Gusenberg = 'weapon_gusenberg',

	/* Sniper Rifles */
	SniperRifle = 'weapon_sniperrifle',
	HeavySniper = 'weapon_heavysniper',
	HeavySniperMk2 = 'weapon_heavysniper_mk2',
	MarksmanRifle = 'weapon_marksmanrifle',
	MarksmanRifleMk2 = 'weapon_marksmanrifle_mk2',
	PrecisionRifle = 'weapon_precisionrifle',

	/* Heavy Weapons */
	Rpg = 'weapon_rpg',
	GrenadeLauncher = 'weapon_grenadelauncher',
	GrenadeLauncherSmoke = 'weapon_grenadelauncher_smoke',
	MiniGun = 'weapon_minigun',
	Firework = 'weapon_firework',
	RailGun = 'weapon_railgun',
	HomingLauncher = 'weapon_hominglauncher',
	CompactLauncher = 'weapon_compactlauncher',
	RayMinigun = 'weapon_rayminigun',
	EmpLauncher = 'weapon_emplauncher',
	RailGunXm3 = 'weapon_railgunxm3',
	SnowLauncher = 'weapon_snowlauncher',

	/* Throwables */
	Grenade = 'weapon_grenade',
	GasBz = 'weapon_bzgas',
	Molotov = 'weapon_molotov',
	StickyBomb = 'weapon_stickybomb',
	ProximityMine = 'weapon_proxmine',
	SnowBall = 'weapon_snowball',
	PipeBomb = 'weapon_pipebomb',
	Ball = 'weapon_ball',
	SmokeGrenade = 'weapon_smokegrenade',
	Flare = 'weapon_flare',
	AcidPackage = 'weapon_acidpackage',

	/* Miscellaneous */
	PetrolCan = 'weapon_petrolcan',
	Parachute = 'gadget_parachute',
	FireExtinguisher = 'weapon_fireextinguisher',
	HazardCan = 'weapon_hazardcan',
	FertilizerCan = 'weapon_fertilizercan',
	NightVision = 'gadget_nightvision',

	/* Unknown */
	HackingDevice = 'weapon_hackingdevice',
	Handcuffs = 'weapon_handcuffs',
	GarbageBag = 'weapon_garbagebag',
	Tranquilizer = 'weapon_tranquilizer',
	MetalDetector = 'weapon_metaldetector',
}
