export enum CloudHat {
    Unknown = 1,
    AltoStratus = 'altostratus',
    Cirrus = 'Cirrus',
    Cirrocumulus = 'cirrocumulus',
    Clear01 = 'Clear 01',
    Cloudy01 = 'Cloudy 01',
    Contrails = 'Contrails',
    Horizon = 'Horizon',
    HorizonBand1 = 'horizonband1',
    HorizonBand2 = 'horizonband2',
    HorizonBand3 = 'horizonband3',
    Horsey = 'horsey',
    Nimbus = 'Nimbus',
    Puffs = 'Puffs',
    Rain = 'RAIN',
    Snowy01 = 'Snowy 01',
    Stormy01 = 'Stormy 01',
    StratosCumulus = 'stratoscumulus',
    Stripey = 'Stripey',
    Shower = 'shower',
    Wispy = 'Wispy',
}
