export enum VehicleWheelType {
    Sport = 0,
    Muscle = 1,
    LowRider = 2,
    Suv = 3,
    OffRoad = 4,
    Tuner = 5,
    Bike = 6,
    HighEnd = 7,
    BennysOriginal = 8,
    BennysBespoke = 9,
    OpenWheel = 10,
    Street = 11,
    Track = 12,
}
