/**
 * You can use this enum containing all material names for the materials in materials.dat file
 *
 * @enum{string}
 */
export enum MaterialEnum {
	None = 0,
	Unk = 'UNK',
	Default = 'DEFAULT',

	// HARD TERRAIN
	Concrete = 'CONCRETE',
	ConcretePothole = 'CONCRETE_POTHOLE',
	ConcreteDusty = 'CONCRETE_DUSTY',
	Tarmac = 'TARMAC',
	TarmacPainted = 'TARMAC_PAINTED',
	TarmacPothole = 'TARMAC_POTHOLE',
	RumbleStrip = 'RUMBLE_STRIP',
	BreezeBlock = 'BREEZE_BLOCK',
	Rock = 'ROCK',
	RockMossy = 'ROCK_MOSSY',
	Stone = 'STONE',
	CobbleStone = 'COBBLESTONE',
	Brick = 'BRICK',
	Marble = 'MARBLE',
	PavingSlab = 'PAVING_SLAB',
	SandstoneSolid = 'SANDSTONE_SOLID',
	SandstoneBrittle = 'SANDSTONE_BRITTLE',

	// LOOSE TERRAIN
	SandLoose = 'SAND_LOOSE',
	SandCompact = 'SAND_COMPACT',
	SandWet = 'SAND_WET',
	SandTrack = 'SAND_TRACK',
	SandUnderwater = 'SAND_UNDERWATER',
	SandDryDeep = 'SAND_DRY_DEEP',
	SandWetDeep = 'SAND_WET_DEEP',
	Ice = 'ICE',
	IceTarmac = 'ICE_TARMAC',
	SnowLoose = 'SNOW_LOOSE',
	SnowCompact = 'SNOW_COMPACT',
	SnowDeep = 'SNOW_DEEP',
	SnowTarmac = 'SNOW_TARMAC',
	GravelSmall = 'GRAVEL_SMALL',
	GravelLarge = 'GRAVEL_LARGE',
	GravelDeep = 'GRAVEL_DEEP',
	GravelTrainTrack = 'GRAVEL_TRAIN_TRACK',
	DirtTrack = 'DIRT_TRACK',
	MudHard = 'MUD_HARD',
	MudPothole = 'MUD_POTHOLE',
	MudSoft = 'MUD_SOFT',
	MudUnderwater = 'MUD_UNDERWATER',
	MudDeep = 'MUD_DEEP',
	Marsh = 'MARSH',
	MarshDeep = 'MARSH_DEEP',
	Soil = 'SOIL',
	ClayHard = 'CLAY_HARD',
	ClaySoft = 'CLAY_SOFT',

	// Vegetation
	GrassLong = 'GRASS_LONG',
	Grass = 'GRASS',
	GrassShort = 'GRASS_SHORT',
	Hay = 'HAY',
	Bushes = 'BUSHES',
	Twigs = 'TWIGS',
	Leaves = 'LEAVES',
	WoodChips = 'WOODCHIPS',
	TreeBark = 'TREE_BARK',

	// Metals
	MetalSolidSmall = 'METAL_SOLID_SMALL',
	MetalSolidMedium = 'METAL_SOLID_MEDIUM',
	MetalSolidLarge = 'METAL_SOLID_LARGE',
	MetalHollowSmall = 'METAL_HOLLOW_SMALL',
	MetalHollowMedium = 'METAL_HOLLOW_MEDIUM',
	MetalHollowLarge = 'METAL_HOLLOW_LARGE',
	MetalChainlinkSmall = 'METAL_CHAINLINK_SMALL',
	MetalChainlinkLarge = 'METAL_CHAINLINK_LARGE',
	MetalCorrugatedIron = 'METAL_CORRUGATED_IRON',
	MetalGrille = 'METAL_GRILLE',
	MetalRailing = 'METAL_RAILING',
	MetalDuct = 'METAL_DUCT',
	MetalGarageDoor = 'METAL_GARAGE_DOOR',
	MetalManhole = 'METAL_MANHOLE',

	// Woods
	WoodSolidSmall = 'WOOD_SOLID_SMALL',
	WoodSolidMedium = 'WOOD_SOLID_MEDIUM',
	WoodSolidLarge = 'WOOD_SOLID_LARGE',
	WoodSolidPolished = 'WOOD_SOLID_POLISHED',
	WoodFloorDusty = 'WOOD_FLOOR_DUSTY',
	WoodHollowSmall = 'WOOD_HOLLOW_SMALL',
	WoodHollowMedium = 'WOOD_HOLLOW_MEDIUM',
	WoodHollowLarge = 'WOOD_HOLLOW_LARGE',
	WoodChipboard = 'WOOD_CHIPBOARD',
	WoodOldCreaky = 'WOOD_OLD_CREAKY',
	WoodHighDensity = 'WOOD_HIGH_DENSITY',
	WoodLattice = 'WOOD_LATTICE',

	// ManMade
	Ceramic = 'CERAMIC',
	RoofTile = 'ROOF_TILE',
	RoofFelt = 'ROOF_FELT',
	FibreGlass = 'FIBREGLASS',
	Tarpaulin = 'TARPAULIN',
	Plastic = 'PLASTIC',
	PlasticHollow = 'PLASTIC_HOLLOW',
	PlasticHighDensity = 'PLASTIC_HIGH_DENSITY',
	PlasticClear = 'PLASTIC_CLEAR',
	PlasticHollowClear = 'PLASTIC_HOLLOW_CLEAR',
	PlasticHighDensityClear = 'PLASTIC_HIGH_DENSITY_CLEAR',
	FibreglassHollow = 'FIBREGLASS_HOLLOW',
	Rubber = 'RUBBER',
	RubberHollow = 'RUBBER_HOLLOW',
	Linoleum = 'LINOLEUM',
	Laminate = 'LAMINATE',
	CarpetSolid = 'CARPET_SOLID',
	CarpetSolidDusty = 'CARPET_SOLID_DUSTY',
	CarpetFloorboard = 'CARPET_FLOORBOARD',
	Cloth = 'CLOTH',
	PlasterSolid = 'PLASTER_SOLID',
	PlasterBrittle = 'PLASTER_BRITTLE',
	CardboardSheet = 'CARDBOARD_SHEET',
	CardboardBox = 'CARDBOARD_BOX',
	Paper = 'PAPER',
	Foam = 'FOAM',
	FeatherPillow = 'FEATHER_PILLOW',
	Polystyrene = 'POLYSTYRENE',
	Leather = 'LEATHER',
	TvScreen = 'TVSCREEN',
	SlattedBlinds = 'SLATTED_BLINDS',

	// Glass
	GlassShootThrough = 'GLASS_SHOOT_THROUGH',
	GlassBulletproof = 'GLASS_BULLETPROOF',
	GlassOpaque = 'GLASS_OPAQUE',
	Perspex = 'PERSPEX',

	// Vehicles
	CarMetal = 'CAR_METAL',
	CarPlastic = 'CAR_PLASTIC',
	CarSoftTop = 'CAR_SOFTTOP',
	CarSoftTopClear = 'CAR_SOFTTOP_CLEAR',
	CarGlassWeak = 'CAR_GLASS_WEAK',
	CarGlassMedium = 'CAR_GLASS_MEDIUM',
	CarGlassStrong = 'CAR_GLASS_STRONG',
	CarGlassBulletproof = 'CAR_GLASS_BULLETPROOF',
	CarGlassOpaque = 'CAR_GLASS_OPAQUE',

	// Liquids
	Water = 'WATER',
	Blood = 'BLOOD',
	Oil = 'OIL',
	Petrol = 'PETROL',

	// Misc
	FreshMeat = 'FRESH_MEAT',
	DriedMeat = 'DRIED_MEAT',

	// Projtex
	EmissiveGlass = 'EMISSIVE_GLASS',
	EmissivePlastic = 'EMISSIVE_PLASTIC',

	// VFX Specific Particles
	VFXMetalElectrified = 'VFX_METAL_ELECTRIFIED',
	VFXMetalWaterTower = 'VFX_METAL_WATER_TOWER',

	// VFX Specific Explosions
	VFXMetalSteam = 'VFX_METAL_STEAM',
	VFXMetalFlame = 'VFX_METAL_FLAME',

	// Physics
	PhysNoFriction = 'PHYS_NO_FRICTION',
	PhysGolfBall = 'PHYS_GOLF_BALL',
	PhysTennisBall = 'PHYS_TENNIS_BALL',
	PhysCaster = 'PHYS_CASTER',
	PhysCasterRusty = 'PHYS_CASTER_RUSTY',
	PhysCarVoid = 'PHYS_CAR_VOID',
	PhysPedCapsule = 'PHYS_PED_CAPSULE',
	PhysElectricFence = 'PHYS_ELECTRIC_FENCE',
	PhysElectricMetal = 'PHYS_ELECTRIC_METAL',
	PhysBarbedWire = 'PHYS_BARBED_WIRE',
	PhysPoolTableSurface = 'PHYS_POOLTABLE_SURFACE',
	PhysPoolTableCushion = 'PHYS_POOLTABLE_CUSHION',
	PhysPoolTableBall = 'PHYS_POOLTABLE_BALL',

	// Natural Motion
	Buttocks = 'BUTTOCKS',
	ThighLeft = 'THIGH_LEFT',
	ShinLeft = 'SHIN_LEFT',
	FootLeft = 'FOOT_LEFT',
	ThighRight = 'THIGH_RIGHT',
	ShinRight = 'SHIN_RIGHT',
	FootRight = 'FOOT_RIGHT',
	Spine0 = 'SPINE0',
	Spine1 = 'SPINE1',
	Spine2 = 'SPINE2',
	Spine3 = 'SPINE3',
	ClavicleLeft = 'CLAVICLE_LEFT',
	UpperArmLeft = 'UPPER_ARM_LEFT',
	LowerArmLeft = 'LOWER_ARM_LEFT',
	HandLeft = 'HAND_LEFT',
	ClavicleRight = 'CLAVICLE_RIGHT',
	UpperArmRight = 'UPPER_ARM_RIGHT',
	LowerArmRight = 'LOWER_ARM_RIGHT',
	HandRight = 'HAND_RIGHT',
	Neck = 'NECK',
	Head = 'HEAD',
	AnimalDefault = 'ANIMAL_DEFAULT',

	// New Materials
	CarEngine = 'CAR_ENGINE',
	Puddle = 'PUDDLE',
	ConcretePavement = 'CONCRETE_PAVEMENT',
	BrickPavement = 'BRICK_PAVEMENT',

	// Special Materials used to identify frag bounds
	PhysDynamicCoverBound = 'PHYS_DYNAMIC_COVER_BOUND',
	VFXWoodBeerBarrel = 'VFX_WOOD_BEER_BARREL',
	WoodHighFriction = 'WOOD_HIGH_FRICTION',

	// Special Versions of these material
	RockNoInst = 'ROCK_NOINST',
	BushesNoInst = 'BUSHES_NOINST',
	MetalSolidRoadSurface = 'METAL_SOLID_ROAD_SURFACE',
	StuntRampSurface = 'STUNT_RAMP_SURFACE',

	// Temp Materials - IN USE
	Temp01 = 'TEMP_01',
	Temp02 = 'TEMP_02',
	Temp03 = 'TEMP_03',
	Temp04 = 'TEMP_04',
	Temp05 = 'TEMP_05',
	Temp06 = 'TEMP_06',

	// Temp Materials - FREE TO USE
	Temp07 = 'TEMP_07',
	Temp08 = 'TEMP_08',
	Temp09 = 'TEMP_09',
	Temp10 = 'TEMP_10',
	Temp11 = 'TEMP_11',
	Temp12 = 'TEMP_12',
	Temp13 = 'TEMP_13',
	Temp14 = 'TEMP_14',
	Temp15 = 'TEMP_15',
	Temp16 = 'TEMP_16',
	Temp17 = 'TEMP_17',
	Temp18 = 'TEMP_18',
	Temp19 = 'TEMP_19',
	Temp20 = 'TEMP_20',
	Temp21 = 'TEMP_21',
	Temp22 = 'TEMP_22',
	Temp23 = 'TEMP_23',
	Temp24 = 'TEMP_24',
	Temp25 = 'TEMP_25',
	Temp26 = 'TEMP_26',
	Temp27 = 'TEMP_27',
	Temp28 = 'TEMP_28',
	Temp29 = 'TEMP_29',
	Temp30 = 'TEMP_30',
}
