name: Node.js Package

on:
  push: 
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check tag matches version pattern
        id: check_tag
        run: |
          echo "Tag: ${{ github.ref }}"
          if [[ "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]] &&
              [[ ! "${{ github.ref }}" =~ SNAPSHOT ]] &&
              [[ ! "${{ github.ref }}" =~ EXPERIMENTAL ]]; then
            echo "Tag matches version pattern and is not SNAPSHOT or EXPERIMENTAL"
            echo "match=true" >> $GITHUB_ENV
          else
            echo "Tag does not match or is excluded"
            echo "match=false" >> $GITHUB_ENV
          fi

      - name: Exit job if tag is not valid
        if: env.match == 'false'
        run: |
          echo "Exiting job because the tag is not valid."
          exit 1
        continue-on-error: true

      - name: Setup Node.js
        if: env.match == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        if: env.match == 'true'
        run: npm ci

      - name: Check Lint
        if: env.match == 'true'
        run: npm run lint

      - name: Run tests
        if: env.match == 'true'
        run: npm test
  
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with npm registry
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Prepare build
        run: npm run prepare

      - name: Publish package to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - name: Post-build message
        run: echo "-- build completed successfully"
